sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start dockerfile"
  - docker build -t sanghaklee/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true sanghaklee/docker-react-app npm run test -- --coverage